use_frameworks!

target 'GSiOSKit_Example' do
  pod 'GSiOSKit', :path => '../'

  target 'GSiOSKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 8.0.0'
  end
end
